### ISSUE TITLE
Tighter Modpack Integration

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#12]
Looking through the pack here there's a few options for some recipes that I think can be added to help tie some the pack together a bit better. Further ideas or critiques are welcome

- General:
  - [x] Recipe to convert 1 Wheat to 1 Seed
- Immersive Engineering:
  - [x] Hatchery Fertilizer Recipe to Mixer (Requires IE 58)
  - [x] Actually Additions Oils to Mixer (Requires IE 58)
- Chisel
  - [x] Check if we can Chisel Railcraft Stones, otherwise add via ModTweaker
- Forestry:
  - [x] Check Farm setting for shape
  - Adventurer's Backpack is unconfigured
    - Should we bother? Replaced by Bag of Holding
  - Additional Stamp Recipes
    - Use Thermal Expansion Coins?
  - Carpenter Recipes
    - [x] Recipe for IE Planks with Creosote
    - [x] Recipe for Impregnated Sticks and Casings using Creosote
    - [x] Recipe for Impregnated Sticks and Casings using Plant Oil
- AgriCraft:  
  - [x] Snad as a valid 'sand_soil'
  - [x] Add Fertilized Soil and Dirt to the appropriate soil types
- Environmental Tech:  
  - [x] Add World Gen Railcraft Stones to Void Resource Miner

**Comment by Vaygrim** [comment]
Regarding these changes:

- I feel like making Ender Lillies a crop would infringe upon the point of the Enderbore Crop. Right now Ender Lilly can be achieved early game, but they are slow. Enderbore Crops get obtained later on, but grow faster.

- Shulker teleports. I'd rather not make this a thing until Metamorph irons out its code nonsense, as right now Endermen are spamming enough. Personally, I almost want to consider Shulkers as boss mobs, and black list them. I think it would make things easier.

- I intentionally didn't add recipes for Bone White, Sand and Quartz chickens as a tip to motivate people to get out and explore a bit. A little wandering resulted in my finding all three of these very easily. Regarding Quartz chickens, there were literally about 6 standing outside my Nether Portal went I first went to the Nether. That being said, if you've had a hard time finding any of these (or others have), we can add recipes sure.

Everything else I'm up for, I just either don't know how to configure them.. or don't have the patience. heh

**Comment by mallrat208** [comment]
I can definitely add that stuff, I just didn't want to add any big changes without first running it by here. 

I've gone ahead and crossed off the three you mentioned from the list

**Comment by RedeyeTheGoblin** [comment]
Can we add "Figure out why Hatchery Fertilized Dirt\Farmland won't work for Agricraft" to the list too? :)

**Comment by mahldcat** [comment]
Did we want to consider ore(fluid)? dictionary entries for seed/plant oil so that immersive engineering oil could work with forestry recipes (and vice versa)...

(for instance IE oil + wood to make the forestry treated wood sticks that are used for the second tier apiary frames)

**Comment by Dragonracer73** [comment]
Make sure the fluids between Ie and forestry can cross talk, ethanol, biodesiel, ect and are useable in the appropriate machines

**Comment by mallrat208** [comment]
I've updated the list with some newer stuff discussed here and in Discord as well as removed the stuff we're passing on for now.

@Dragonracer73 It's important to note that while the IE and Forestry fluids are similar, they are intentionally not the same fluids.  We can definitely see about adding some cross compatibility but I would favor the mod's original fluids over others. For example, if we want to use Plant Oil from IE or even Canola Oil from Actually Additions in Forestry, I would say it should take slightly more than what it would take when using the intended fluid, Seed Oil.

**Comment by mallrat208** [comment]
Added initial pass for this in PR #13

**Comment by Vaygrim** [comment]
Closing this as part of the 1.2 release.
