### ISSUE TITLE
Client side crash when exiting or entering nether portal

### ISSUE THREAD

**Issue by Veggetossj** [Vaygrim/CoopLife#14]
When I entered the nether today at a similar time to Gabbroboccia we both got a red screen (looked like netherrack red to me) and had to relog to be able see things in the nether. After that i wanted to exit the Nether through my own portal in the Nether and upon teleporting to the overworld met with a client side crash (1). After restarting my client and reading Discord while logging in, I crashed again upon hearing the nether portal teleporting sound(2).

Crashlog 1: https://pastebin.com/tUQPGGmT
Crashlog 2: https://pastebin.com/ZCeMbdeV

**Comment by Vaygrim** [comment]
This stems from a combination of threaded code in ATG, and Optifine being installed. Has been reported to the ATG author. Closing issue.
