### ISSUE TITLE
AgriCraft: Crash when crops are destroyed by flowing water

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#19]
Pack Version: 1.12
Crash Report: https://gist.github.com/mallrat208/39a009ed8a60c5064458494562ace93e
Mod Version: AgriCraft 2.0.0-0.8.0-a15

We had a series of crashes caused by flowing water washing up AgriCraft crops that were planted above a Forestry Multifarm. The Crash Report itself indicates that the AgriCraft crops returned a null itemstack for the creation of an EntityItem to be spawned in world causing _**Bad Things**_<sup>**TM**</sup>.

We were able to remove the water using  ```/cofh clearblocks x1 y1 z1 x2 y2 z2 water``` and load the chunks back up with no further issues.

This appears to have been fixed in dev of AgriCraft and will be corrected in a future release, AgriCraft/AgriCraft#923

**Comment by mallrat208** [comment]
Initial testing with AgriCraft 2.0.0-0.9.0-a16 and InfinityLib 0.9.0 indicates this crash is indeed fixed. I've been unable to reproduce it locally.

**Comment by mallrat208** [comment]
As an Update to this;

It won't crash anymore but it does add a bit of log spam whenever it would have crashed.

**Comment by Vaygrim** [comment]
I'll close this out once we update to the next version.
