### ISSUE TITLE
Iron Ingots

### ISSUE THREAD

**Issue by Dragonracer73** [Vaygrim/CoopLife#2]
Unidict needs adjustment for iron ingots. They are set to agricraft atm. Unable to craft certian recipies with them, IE tool racks for cooking with blockheads. Nuggets will not reconvert back to ingots or in a compacting drawer.

**Comment by Dragonracer73** [comment]
upon further testing it seems the agricraft nuggets in particular are the non craftable culprit

**Comment by Vaygrim** [comment]
Solved in PR #4
