### ISSUE TITLE
Additional CraftTweaker Recipes

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#20]
Some things that could possibly use recipes:

### Chisel Concrete and Concrete Powder
Chisel Concrete is essentially a backported version of 1.12's Concrete. It is created by having Concrete Powder touch a water block. Does not have to consume said block. 

While a neat mechanic, it's not a terribly server friendly way to craft the Concrete if you need it in any large quantities. (Easiest Option? Botania or ExU2)
For a recipe I'd say just do 8 Powder Concrete + Water Item yields 8 Concrete of the appropriate color. We can also add a Carpenter Recipe to allow easier automation

We should also add in a recipe to convert between the various colors of Concrete.  8 Concrete + 1 Dye. We could do the same for the Concrete Powder as well.

### Shear Consistency
Add Recipes using Thermal Foundation and Railcraft Shears and to craft Wire from Plates like vanilla Shears can
This includes Copper Wire, Electrum Wire, Aluminum Wire, and Steel Wire

### Chickens
Lava Eggs as Furnace Fuel (same value as Lava Buckets)

### AgriCraft
Carrot to Carrot Seed

### More Poop Processing
Forestry Fermenter or Squeezer perhaps?

**Comment by Vaygrim** [comment]
I like these recipe ideas, especially the wire / shear recipes.
I seem to remember you discussing machines that had a liquid input.. and how our selection was rather limited. Do we need to see about finding a mod that fills that niche?

**Comment by Vaygrim** [comment]
Merged!

**Comment by mallrat208** [comment]
Regarding the lack of machine, I just need to finish a project I've been seriously over complicating for no good reason

**Comment by mallrat208** [comment]
Closing this out since most of these were implemented in #22
