### ISSUE TITLE
Mod Request: Barkifier

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#27]
Curse Link: https://mods.curse.com/mc-mods/minecraft/253042-barkifier

Summary:
Barkifier adds adds an item called a 'Barkifier' to the game. When used on a Log block, the Barkifier converts the block into a version with no set axis. This ends up creating a block that is wood bark on all 6 sides. It is compatible with Vanilla and Forestry as well as some other mods not in Coop Life.

While we can currently create something similar with Chisels and Bits, this option is way friendlier for performance as it's actually a default feature of the block, just one that's normally inaccessible.

**Comment by Vaygrim** [comment]
It's simple, I like!
