### ISSUE TITLE
Immersive Engineering: Client Crash when inserting Red Orchid into Cloche

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#29]
Pack Version: 1.3
Forge: 12.18.3.2281
Immersive Engineering: 0.10-58
ExU2: 1.10.2-1.4.1
Crash Report: https://gist.github.com/mallrat208/6467eeb2f95ddc6cfd38308780b1666d

We ran into this earlier when someone inserted a Red Orchid inside of a Cloche. They experienced a client crash shortly (or immediately? not clear) afterwards.

We were able to remove the offending block using the COFH ClearBlocks command and everything is shiny at the moment.

Care should be taken with the Cloche and using Red Orchid and most likely Ender Lily seeds.

This has previously been reported to the mod author BluSunrize/ImmersiveEngineering#2071

**Comment by Vaygrim** [comment]
I take it the Cloche has no blacklist for plants?

**Comment by mallrat208** [comment]
Nope. 

We've got to wait for a bug fix update to IE or disable the Cloche.

**Comment by AtomicBlom** [comment]
Based on the bugfix mentioned in that issue, if you can't get Blu to backport the fix to 1.10.2, you might be able to ask ExU to not return null from getQuads(). If they returned an empty list IE wouldn't break.

**Comment by malte0811** [comment]
Where exactly does the idea of XU returing null quads come from? XU is returning an immutable list, IE tries to add new quads to that list and crashes since immutable lists are there to prevent such addition (or removal, but that is irrelevant here).

**Comment by AtomicBlom** [comment]
Yup, my bad. I must have skim read the crash report.

**Comment by mallrat208** [comment]
This should be fixed as of IE 0.10-60

**Comment by mallrat208** [comment]
Fixed as of 1.51
