### ISSUE TITLE
Copper ingots from a Dungeon Loot chest (Village smithy chest) do not "link" properly to other in game ingots

### ISSUE THREAD

**Issue by mahldcat** [Vaygrim/CoopLife#3]
General discovery steps:

1) Village smithy chest had several copper ingots.
2) Later went to craft the thermal expansion's basic portable tank, and it would not recognize the ingots
3) I double checked the ingots in the recipe and they were a different mod than the ones I had in inventory
4) Likewise they differed from the ingots dropped by the copper chicken

(I do NOT have the mod they were from handy, but when I jump back on later on, will update this issue with the origin mod)

**Comment by mallrat208** [comment]
This is definitely caused by UniDict.

That said it's got to be from either Immersive Engineering or Railcraft. I don't believe we can actually remove those from worldgen. We could possibly override any existing loot tables that are used, but if they're doing so the old way it won't work.

**Comment by Vaygrim** [comment]
Corrected in PR #4
