### ISSUE TITLE
Crash when Trading with Railcraft Villager

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#7]
Pack Version 1.11
Crash Report: https://gist.github.com/mallrat208/174201d6fa1a51ec50b186c981923127

We ran into a server crash when someone was trying to trade with one of the Railcraft Villagers. For now I'd recommend avoiding them.

**Comment by Vaygrim** [comment]
Closing as part of the 1.2 release, since we have a temporary solution in place via Villager Trade Tables
