### ISSUE TITLE
Ingots returning wrong nugget type when crafted in Vanilla crafting table

### ISSUE THREAD

**Issue by Gyvavaizdis** [Vaygrim/CoopLife#8]
when an ingot is put into a crafting table  it tells the player that the outcome will be 9 RAILCRAFT nuggets. but when the nuggets are crafted instead you get 9 AGRICRAFT nuggets which dont seem to work in recipes.(edited)
so far I have tested all the metals I can think of and the following were affected.
Iron
Lead
Copper
Silver
Nickel 
Aluminum
tin
Platinum

The nuggets seem to not be able to be used for any crafting even the recipe to turn them back into their respective ingot form

**Comment by mallrat208** [comment]
This should be taken care of with #16
