### ISSUE TITLE
Massive Console Spam due to NEI

### ISSUE THREAD

**Issue by mallrat208** [Vaygrim/CoopLife#9]
Pack Version: 1.11

Ran into a crash yesterday that tipped me off to there being a problem. It seems like NEI is catching and logging a TON of errors with it's filtering routines even if you set the Searchbox to default to JEI

This is an existing issue that has already been reported at https://github.com/TheCBProject/NotEnoughItems/issues/93

**Comment by mallrat208** [comment]
It looks like the only corrective action at the moment may be to downgrade to NEI 2.1.3.207

**Comment by Vaygrim** [comment]
I'm going to test the 'lowercase fix' later tonight. If it indeed solves our problems, I'm going to roll out a 1.12 update tomorrow or Wednesday. We can downgrade versions of NEI then.

**Comment by Vaygrim** [comment]
Latest update of NEI being included in the pack will resolve this issue finally.
